import type { AppData } from './types'

export const createId = (prefix: string) =>
  `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`

export const initialData: AppData = {
  schemaVersion: 1,
  settings: {
    theme: 'dark',
    activeTrackId: 'track-learning',
  },
  hobbies: [
    {
      id: 'hobby-physics',
      name: 'Study physics',
      category: 'Learning',
      color: '#7c3aed',
      effort: 'high',
      priority: 1,
      targetHours: 10,
      status: 'active',
      notes: 'Deep work topic. Rotate after a meaningful block is complete.',
    },
    {
      id: 'hobby-japanese',
      name: 'Learn Japanese',
      category: 'Learning',
      color: '#db2777',
      effort: 'high',
      priority: 2,
      targetHours: 8,
      status: 'active',
      notes: 'Keep sessions short enough to start on low energy days.',
    },
    {
      id: 'hobby-piano',
      name: 'Learn piano',
      category: 'Skill',
      color: '#0891b2',
      effort: 'medium',
      priority: 3,
      targetHours: 5,
      status: 'active',
      notes: 'Practice rhythm and hand independence.',
    },
    {
      id: 'hobby-chess',
      name: 'Play chess',
      category: 'Play',
      color: '#16a34a',
      effort: 'low',
      priority: 4,
      targetHours: 3,
      status: 'active',
      notes: 'Effortless hobby. Track without letting it crowd out learning.',
    },
    {
      id: 'hobby-reading',
      name: 'Reading',
      category: 'Recovery',
      color: '#f59e0b',
      effort: 'low',
      priority: 5,
      targetHours: 4,
      status: 'active',
      notes: 'Useful for winding down while still feeling nourished.',
    },
    {
      id: 'hobby-gaming',
      name: 'Gaming',
      category: 'Leisure',
      color: '#ef4444',
      effort: 'low',
      priority: 6,
      targetHours: 4,
      status: 'active',
      notes: 'Keep visible so it stays intentional.',
    },
  ],
  tracks: [
    {
      id: 'track-learning',
      name: 'Learning queue',
      description: 'One demanding hobby at a time. Finish the hour block, then rotate it down.',
      mode: 'queue',
      hobbyIds: ['hobby-physics', 'hobby-japanese', 'hobby-piano'],
      oneAtATime: true,
      defaultTargetHours: 10,
      rotateOnCompletion: true,
    },
    {
      id: 'track-effortless',
      name: 'Effortless hobbies',
      description: 'Low activation hobbies that should be tracked and bounded, not forced.',
      mode: 'free',
      hobbyIds: ['hobby-chess', 'hobby-reading', 'hobby-gaming'],
      oneAtATime: false,
      defaultTargetHours: 4,
      rotateOnCompletion: false,
    },
  ],
  sessions: [],
  allocations: [
    { id: 'allocation-learning', category: 'Learning', weeklyHours: 8 },
    { id: 'allocation-skill', category: 'Skill', weeklyHours: 4 },
    { id: 'allocation-play', category: 'Play', weeklyHours: 3 },
    { id: 'allocation-recovery', category: 'Recovery', weeklyHours: 5 },
    { id: 'allocation-leisure', category: 'Leisure', weeklyHours: 4 },
  ],
}
